var instrument = require("../instrument");

module.exports = function(bot) {
	bot.newCommand("talk dirty", function() {
		var words = {
			maleGenital : [
				' USB-plug',
				' VGA-Kabel',
				'e Externe Festplatte',
				'e PCI-Express-Card',
				'e Erweiterungskarte',
				'en USB-Stick',
				'e S-D-Card',
				'en 3.5 Millimeter Kopfhörer Stecker',
				'en Penis',
				'en übergroßen Penis',
				'en überlangen Penis',
				'en Riesen-Penis',
				'en dicken Penis',
				' Liebstöckel',
				' Joystick',
				'e Porreestange',
				' drittes Bein',
				' Schwanz',
				' Ringelschänzchen',
				' primäres Geschlechtsorgan',
				'e wilde Nacktschnecke',
				"en 12-Pfund-Dorsch",
				"en 30er Kolben",
				" Alimentenkabel",
				" Allmoprala",
				" Almowala",
				" AlMoWaPRaLA",
				"en Ast",
				"e Babyanakonda",
				"en Beckenbrecher",
				"en Beckenmörser",
				"en Befruchtungsmuskel",
				" blaugeädertes Unding",
				"en Blutschlauch",
				"e Blutwurst",
				"e Bockwurst mit Pulsschlag",
				"en Bommelmax",
				" Bonbon aus Wurst",
				" Bubenspätzle",
				" Chromopila",
				" Chromoprala",
				" Chromopralula",
				" Chromowala",
				" dickadriger Bestrafer",
				" dickes Gerät",
				" Ding-Dong",
				" Dingdong",
				" Dong",
				"en Druckschlauch",
				"en Dumbledor",
				"en Dünnbrettbohrer",
				"e einäugige Hosenschlange",
				"e einäugige Speikobra",
				"en einäugigen Glatzenaal",
				"e Eiweißtuba",
				" erhobenes Zepter der Liebe",
				"en Eselsriemen",
				"e Fellstanze",
				"en Feuerwehrhelm",
				"en Feuerwehrmann",
				"en Fickbolzen",
				" Fleischeclaire mit Sahnefüllung",
				"e Fleischflöte",
				" Fleischgewehr",
				"en fleischgewordenen Bohrhammer",
				"en fleischigen Rohrstock",
				"en Fleischjoystick",
				"en Fleischlolli",
				"en Fleischlutscher",
				"en Fleischmeißel",
				" Fleischmikrofon",
				"e Fleischpeitsche",
				"e Fleischrakete",
				"e Fleischsonde",
				"e Fleischzigarre",
				"en Fotzenhobel",
				"en Frümosuprala",
				" Gehänge",
				"e Gelbwurzel",
				"en Generalstabskanonier",
				"en Genitalexpander",
				"en Genitalhydrant",
				"e Gentube",
				"e Genusswurzel",
				"e Gewürzgurke",
				"e Gromopila",
				"e GuMoLa",
				"e harten Tatsachen",
				"en Hartfleischkolben",
				"en Hauptgenerator",
				"e Himmelslanze",
				"e Hormonlanze",
				"en Hosenrochen",
				"en Hosenwurm",
				"en Hulk Hoden",
				"en Illo",
				"en Jackhammer",
				"en Johannes",
				"en Johannes und die Zwillinge",
				"en Johny",
				"en Joystick",
				"en Jungfernschreck",
				"en Kasper",
				"en Kingpint",
				"en Kniebinder",
				"en Körperstöpsel",
				"e Kromorpila",
				"e Kromorpralula",
				"e Kronjuwelen",
				"e Krücke",
				"en Lachs",
				"e Lanze",
				"en Le Prügel",
				"e Lehmstange",
				"en Liebesknochen",
				"e Liebeslanze",
				"en Liebeslolli",
				"en Liebesstengel",
				"en Löres",
				"en Lötkolben",
				"en Lurch"
			],
			femaleGenital : [
				'en USB-Port',
				'en VGA-Port',
				'e 3.5mm Kopfhörer Buchse',
				' CD-Rom Laufwerk',
				'en P S 2 Port',
				'en CPU Sockel',
				'en Speicherslot',
				'en P C I-Express-Slot',
				'en Blubber',
				'e Miesmuschel',
				'e Miefmuschel',
				'en Fischladen',
				"en aufgeplatzten Igel",
				"en begehbaren Schrank",
				" Bohrloch",
				" Brötchen",
				"en Brummer",
				" Crashzentrum",
				"e Dehnungsfuge",
				"e Dose",
				"e Edelpflaume",
				"e Einflugschneise",
				" Feuchtbiotop",
				" Feuchtgebiet",
				"en Fickschlitz",
				"en Fickspalt",
				" Fischbrötchen",
				"e Fischers Ritze",
				"en Fischladen",
				"e Fischpflaume",
				"e Fischritze",
				" Fischschacht",
				"e Fleischfalte",
				"en Fleischlappen",
				"n flüsterndes Auge",
				"e Fotze",
				" Fotzenfleisch",
				"en Frosch",
				"e Fudde",
				"e Futte",
				"e Gekrösemöse",
				"e Gletscherspalte",
				"en Hamburger",
				"e Heimat des purpurhelmigen Kriegers",
				"e Höllgrotte",
				" Jadekästchen",
				" Knallloch",
				" Kühllufteinlass",
				"e Lachshöhle",
				" Land des senkrechten Lächelns",
				"en Liebespudding",
				"e Lustgrotte",
				"e Matschpflaume",
				"e Mädchenschmatze",
				"e Mimmi",
				"e Modderhöhle",
				"e Moosmuschi",
				"e Mulle",
				"e Mumu",
				"e Muschel",
				"e Muschmusch",
				" Nillenetui",
				"e offene Fleischwunde",
				"e Pflaume",
				"e Pimmelgarage",
				" Pink Taco",
				"e Pony-Schnute",
				"e Puschemauke",
				" Reinspritzschlitz",
				" rosa Innenfutter",
				"e Rotzefotze",
				"e Sackgasse",
				" Salamiversteck",
				"en Samencontainer",
				"e Samensammelstelle",
				" Schatzkäschtle",
				"e Scheuerpflaume",
				"e Schlabberfotze",
				" Schlammloch",
				" Schlatzfut",
				"en Schlitz",
				"e Schnulle",
				"e Schwanzgarage",
				"e Schwanzschatulle",
				"e Schwanzstube",
				" Senfglas",
				" Siffloch",
				" Spritznest",
				" Spritzritz",
				" Staubloch",
				" Stinkschlitz",
				"en Stoßfänger",
				"en Strudelfutt",
				"e Taschenmuschi",
				"e Tropfsteinhöhle",
				"e V-Zone",
				" Vertikalgrinsen",
				"e Wachstumsfuge",
				" Wurstfach",
				" Zentralloch"
			],
			action : [
				'stecke',
				'einstecke',
				'anschließe',
				'ramme',
				'schweisse'
			],
			pettingAction : [
				'überlade',
				'überschreibe',
				'aktiviere',
				'berühre',
				'zerstöre',
				'entferne',
				'übertakte',
				'debugge',
				'streichele',
				'fiste',
				'beisse',
				'kneife',
				'schlage',
				'knete',
				'liebkose',
				'leck'
			],
			pettingZone : [
				'e Festplatte',
				'en Touchscreen',
				'e C P U',
				'e Grafikkarte',
				'e North bridge',
				' Mainboard',
				'en Speicher',
				'e S S D',
				' Netzteil',
				'en L3-Cache',
				'en Kernel',
				'en Bootloader',
				' BIOS',
				'e Firmware',
				"e Brüste",
				"en Busen",
				"e Melonen",
				"e Möpse",
				" Plastik",
				"e Skulptur",
				"e Statue",
				"e weibliche Brust",
				"e Airbags",
				"en Atombusen",
				"e Atomic Titten",
				"e Babytränke",
				"e Duddeln",
				"e Euter",
				"e Gazongas",
				"e Glocken",
				"e Hupen",
				"e Membel",
				"e Milchbehälter",
				"e Milchferkel",
				"e Milchkanister",
				"e Milchtheke",
				"e Milchtüten",
				"e Molkerei",
				"e Mopedlampen",
				"e Moppelklampen",
				"e Mopsbälle",
				" Mopshausen",
				"e Ömmel",
				"en Plasmabusen",
				"e Quarktaschen",
				"e Saugfelder",
				"e Schleudereuter",
				" Schleudergesäuge",
				"e Schlöpse",
				"e Schüsselbrüste",
				" Titt und Tott",
				" Tittail",
				"e Titten",
				"e Tutteln",
				"e Vollwertmilchtüten",
				"en Vorbau",
				"e Zwillinge"
			],
			attribute : [
				'heiss',
				'übertaktet',
				'fehlerhaft',
				'limited edition',
				'verbessert',
				'kaputt',
				'modifiziert',
				'veraltet',
				'buggy',
				'intern',
				'extern',
				'geil',
				'scharf',
				'erregt',
				'feucht',
				'hart',
				'steif'
			],
			adverb : [
				'schnell',
				'langsam',
				'mit 1000 Megabytes pro Sekunde',
				'hart',
				'härter',
				'feucht',
				'zärtlich'
			]
		};

		var sentences = [
			'Ich will mein{{maleGenital}} in dein{{femaleGenital}} {{action}}n.',
			'Bitte {{action}} mir mein{{maleGenital}}.',
			'Lass uns mein {{attribute}}{{maleGenital}} und dein {{attribute}}{{femaleGenital}} {{adverb}} {{action}}n.',
			'{{pettingAction}} mir mein{{pettingZone}}, Schlampe!',
			'Ohh, ja, bitte {{pettingAction}} mein{{pettingZone}}! Ich bin so {{attribute}}!',
			'Mmh, das macht  mein{{pettingZone}} so {{attribute}}.',
			'Ich liebe dein{{femaleGenital}}. Du bist so  {{attribute}}!',
			'Ich liebe dein{{maleGenital}}. Du bist so  {{attribute}}!',
			'Lass mich dein{{femaleGenital}} {{pettingAction}}n.',
			'Lass mich dein{{maleGenital}} {{pettingAction}}n.',
			'Oooh, bitte {{pettingAction}} mein{{maleGenital}} {{adverb}}.',
			'Oooh, bitte {{pettingAction}} mein{{femaleGenital}} {{adverb}}.',
			'Ich glaube, mein{{pettingZone}} ist grade {{attribute}} geworden!',
			'Pass auf, oder ich {{pettingAction}} dein{{pettingZone}}.',
			'Du bist so {{attribute}}!',
			'Ich will, dass du mein{{pettingZone}} {{pettingAction}}st.'
		];
		bot.say(instrument(sentences, words));
	}, "Gibt eine zufällig generierte erotische Bemerkung aus.", "female");
};
