stages:
  - test
  - deploy

build:
  image: "node:8"
  before_script:
    - yarn install
  script:
    - yarn build:web:release
    - yarn build:server
  stage: test
  cache:
    key: "$CI_PROJECT_ID"
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/
      - server/
      - src/
      - package.json
      - yarn.lock
      - scripts/
      - schema.sql
      - CHANGELOG.md
      - typings/
      - README.md

lint:
  image: "node:8"
  before_script:
    - yarn install
  script:
    - yarn lint:src
    - yarn lint:style
  stage: test
  cache:
    key: "$CI_PROJECT_ID"
    paths:
      - node_modules/

deploy:
  image: "alpine:3.5"
  before_script:
    - apk --update add ansible git openssh python py2-pip
    - mkdir ~/.ssh
    - echo "$SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - cd deploy
    - ansible-playbook mumble-bot.yml --extra-vars "database_password='$DATABASE_PASSWORD' bot_key='$BOT_KEY'"
  dependencies:
    - build
  stage: deploy
  when: manual
  only:
    - master
