import { Column, PrimaryGeneratedColumn, Entity, ManyToOne } from "typeorm";
import { is, scope, DataType, uuid } from "hyrest";
import { world, createMumbleLink, deleteMumbleLink } from "../scopes";
import { User } from ".";

/**
 * A Mumble user representation in the database used for storing linkage from mumble user to database users.
 */
@Entity()
export class MumbleLink {
    @PrimaryGeneratedColumn("uuid")
    @scope(world, deleteMumbleLink) @is().validate(uuid)
    public id?: string;

    /**
     * Unique id as generated by the mumble server.
     */
    @Column("int")
    @scope(world, createMumbleLink) @is(DataType.int)
    public mumbleId?: number;

    /**
     * The id of the user in the database.
     */
    @ManyToOne(() => User, user => user.mumbleLinks)
    @is() @scope(world, createMumbleLink)
    public user?: User;
}
