import { Column, PrimaryGeneratedColumn, Entity, ManyToOne } from "typeorm";
import { is, scope, DataType, uuid } from "hyrest";
import { world, createMumbleLink } from "../scopes";

import { DatabaseUser } from ".";

/**
 * A Mumble user representation in the database used for storing linkage from mumble user to database users.
 */
@Entity()
export class MumbleLink {
    @PrimaryGeneratedColumn("uuid")
    @scope(world) @is().validate(uuid)
    private id?: string;

    /**
     * Unique id as generated by the mumble server.
     */
    @Column("int")
    @scope(world, createMumbleLink) @is(DataType.int)
    public mumbleId?: number;

    @Column("varchar", { length: 128 })
    @scope(world, createMumbleLink) @is()
    public name?: string;

    /**
     * The in the database.
     */
    @ManyToOne(() => DatabaseUser, user => user.mumbleLinks)
    @is() @scope(world, createMumbleLink)
    public user?: DatabaseUser;
}
