/**
 * A Mumble user representation in the database used for storing linkage from mumble user to database users.
 */
export interface MumbleDatabaseUser {
    /**
     * Unique id as generated by the mumble server.
     */
    id: number;
    /**
     * The username of the user in the mumble server.
     */
    username: string;
}
