---

- name: create database
  postgresql_db:
    name: jenny
    login_password: "{{ database_password }}"
    login_user: "prior"
    state: present

- name: install extensions in database
  postgresql_ext:
    db: jenny
    name: uuid-ossp
    login_password: "{{ database_password }}"
    login_user: "prior"
    state: present

- name: create directory
  file: path=/home/prior/applications/mumble-bot state=directory

- name: copy files
  synchronize:
    src: "{{ item }}"
    dest: /home/prior/applications/mumble-bot
  with_items:
    - ../server
    - ../package.json
    - ../yarn.lock
    - ../typings
    - ../README.md

- name: configure
  template:
    src: config.yml.j2
    dest: '/home/prior/applications/mumble-bot/config.yml'

- name: add private key
  copy: content="{{ bot_key }}" dest=/home/prior/applications/mumble-bot/bot.key

- name: add cert
  template:
    src: bot.cert.j2
    dest: '/home/prior/applications/mumble-bot/bot.cert'

- name: install node
  unarchive:
    src: https://nodejs.org/dist/v{{ node_version }}/node-v{{ node_version }}-linux-x64.tar.xz
    dest: /home/prior/applications/mumble-bot
    remote_src: yes

- name: install dependencies
  shell: 'npm install yarn && ./node_modules/.bin/yarn'
  args:
    chdir: /home/prior/applications/mumble-bot
  environment:
    PATH: "/home/prior/applications/mumble-bot/node-v{{ node_version }}-linux-x64/bin:{{ ansible_env.PATH }}"

- name: add systemd unit files
  template:
    src: '{{ item }}.j2'
    dest: '/home/prior/.config/systemd/user/{{ item }}'
  with_items:
    - mumble-bot.service

- name: enable and start the services
  service:
    name: '{{ item }}'
    state: restarted
    enabled: yes
    daemon-reload: yes
    user: yes
  with_items:
    - mumble-bot
