import {
    Column,
    PrimaryGeneratedColumn,
    Entity,
    ManyToOne,
    OneToMany,
    CreateDateColumn,
    UpdateDateColumn
} from "typeorm";
import { is, scope, DataType, oneOf, specify, required, length, uuid, transform } from "hyrest";
import { world, login } from "../scopes";

/**
 * A Mumble user representation in the database used for storing linkage from mumble user to database users.
 */
@Entity()
export class MumbleDatabaseUser {
    @PrimaryGeneratedColumn("uuid")
    @scope(world) @is().validate(uuid)
    private id?: string;

    /**
     * Unique id as generated by the mumble server.
     */
    @Column("int")
    @scope(world) @is(DataType.int)
    public mumbleId: number;

    /**
     * The username of the user in the mumble server.
     */
    @Column("varchar", { length: 100 })
    @is() @scope(world)
    public username: string;
}
