---

- name: create directory
  file: path=/storage/prior/applications/mumble-bot-frontend state=directory

- name: copy files
  synchronize:
    src: "{{ item }}"
    dest: /storage/prior/applications/mumble-bot-frontend/
  with_items:
    - ../dist/*.css
    - ../dist/*.css.map
    - ../dist/*.html
    - ../dist/*.js
    - ../dist/*.js.map
    - ../dist/*.png

- name: configure
  template:
    src: config.js.j2
    dest: '/storage/prior/applications/mumble-bot-frontend/config.js'
