---

- name: create directory
  file: path=/storage/prior/applications/mumble-bot-frontend state=directory

- name: copy files
  synchronize:
    src: "{{ item }}"
    dest: /storage/prior/applications/mumble-bot-frontend/
  with_items:
    - ../4436bbb2f5743bc96272c1ff7ac30d87.png
    - ../bundle.css
    - ../bundle.css.map
    - ../bundle.js
    - ../bundle.js.map
    - ../index.html

- name: configure
  template:
    src: config.js.j2
    dest: '/storage/prior/applications/mumble-bot-frontend/config.js'
