var instrument = require("../instrument");
var Winston = require("winston");

module.exports = function(bot, callback) {
	var words = {
		attribute : [
			"hässlich",
			"stinkend",
			"miefend",
			"abgeranzt",
			"fett",
			"nutzlos",
			"wertlos",
			"käsig",
			"gammelig",
			"spermaschluckend",
			"penislutschend",
			"schwul",
			"behindert",
			"angekackt",
			"kackig",
			"fotzig",
			"müllig",
			"ranzig",
			"ölig",
			"pädophil",
			"cheatend",
			"fischig",
			"dumm",
			"hirnrissig",
			"gehirnamputiert",
			"bekloppt",
			"parasitär",
			"pickelgesichtig",
			"ranzig",
			"ekelhaft",
			"missgestaltet",
			"widerlich",
			"entstellt",
			"minderwertig",
			"wertlos",
			"zurückgeblieben",
			"blöd",
			"begriffsstutzig",
			"enfältig",
			"ungebildet",
			"lästig",
			"geistesgestört",
			"minderbegabt",
			"debil",
			"übel riechend",
			"verpestet",
			"unappetitlich",
			"abgelaufen",
			"brünstig",
			"lüstern",
			"schleimig",
			"müffelig",
			"faulig",
			"mverdorben",
			"verfault",
			"verrottet",
			"schmierig",
			"tranig",
			"fettig",
			"aufgedunsen",
			"gettleibig",
			"aufgebläht",
			"seifig",
			"gemästet"
		],
		subject : [
			"es Stück Scheisse",
			"es Arschloch",
			"er Wichsfrosch",
			"e Sau",
			"es Schwein",
			"er Mongojunge",
			"er Kloputzer",
			"er Kackhaufen",
			"er Scheissefresser",
			"e Schwuchtel",
			"e Wurstuschi",
			"e Bitsch",
			"e Wichs hure",
			"er Spasti",
			"er Hurensohn",
			"er Spastiker",
			"er Behindi",
			"er Arschficker",
			"er Mösenfurz",
			"er Sackpickel",
			"es Mistschwein",
			"er Mongowixer",
			"er Pisser",
			"er Affe",
			"er Affenarsch",
			"es Affenkotstück",
			"er Affenmensch",
			"er Allmachtsdackel",
			"er Ameisenficker",
			"er Analbaron",
			"er Analdin",
			"e Analraupe",
			"e anorektische Fettsau",
			"es Anti-Talent",
			"e Arschbratze",
			"er Arschforscher",
			"es Arschfotzengesicht",
			"es Arschgesicht",
			"e Arschhaarbartfratze",
			"er Arschkeks",
			"er Arschkopf",
			"e Arschlocke",
			"er Aso",
			"er Atomspast",
			"er Auspuffbumser",
			"es Behindikind",
			"er Besen",
			"er Birkenstockfotzenkopf",
			"er Blödfisch",
			"e Bodendompteuse",
			"er Braunkohlebohrer",
			"e Brunskuh",
			"e Bumsnuss",
			"er Buschmensch",
			"e Butterkuh",
			"er Computerflüsterer",
			"er Dauerlutscher",
			"er Dollbohrer",
			"e Donnerfotze",
			"er Doppeldepp",
			"e Dreilochnutte",
			"er Ast",
			"er Dünnschissgurgler",
			"er Eichelarschkopf",
			"er Ekelbob",
			"er Fäkalterrier",
			"e Flattermuschi",
			"er Fontanellenfick",
			"e Fotze",
			"er Fotzklotz",
			"er Fusselbart",
			"er Gesichtseintopf",
			"er Gesichtsgünter",
			"er Gnarf",
			"es Großhirnkastrat",
			"e Hackfresse",
			"er Halbaffe",
			"es Hausschuhgesicht",
			"er Hodenbussard",
			"er Hodenkopf",
			"er Hodenschrubbler",
			"e Hohlbratze",
			"e hohle Fritte",
			"er Honk",
			"er Hosentaschen Godzilla",
			"e Hutze",
			"er Hübi",
			"er Intelligenzverweigerer",
			"er Kackbatzen",
			"er Kackstrumpf",
			"er Kanisterkopf",
			"er Kotlutscher",
			"er Kotzkannenfressbrett",
			"e Kotzkrücke",
			"es Krapfengesicht",
			"es Kuttenluder",
			"e Larve",
			"er Lattenheinrich",
			"er Loser",
			"e Nougatnutte",
			"er Opferspast",
			"e Orgasmusbremse",
			"e Nebenexistenz",
			"es Partyopfer",
			"er Peniskopf",
			"er Penisprothesenträger",
			"e Penisschlampe",
			"e Pferdefresse",
			"er Pfingstochse",
			"er Spritzbock",
			"er Pimmel",
			"e Pimmelfresse",
			"er Pimmelkopf",
			"er Pimmelpapagei",
			"e Quermöse",
			"er Rotzpupsi",
			"e Sackfotze",
			"er Scheißhacken",
			"er Schlabberlappen",
			"er schleimscheißender Bambusaffe",
			"es Schmalzgrab",
			"e Schmalztitte",
			"er schnarchzapfiger Rüsselsack",
			"er Schuhputzer",
			"er Schüttler",
			"e Senfgurke",
			"er Spongebob",
			"er Staubbeutel",
			"e Steroidbeule",
			"er Steroidmutant",
			"e Swarowski-Möse",
			"es Tapetengerippe",
			"er tapezierter Knochen",
			"er Tittenfisch",
			"es Topmoppel",
			"es Unwerk",
			"er Vollaffe",
			"e vollgepisste Strumpfhose",
			"e vollgeschissene Menschenhülle",
			"er Vollmongo",
			"e Wachsfresse",
			"er Waldwichtel",
			"e Wichsbazille",
			"er Wichsfisch",
			"er Zahnspangenbettler",
			"es zoologisches Abfallprodukt"
		],
		food : [
			"Käse",
			"Wurst",
			"Schokolade",
			"Nutella",
			"Kot",
			"Smegma",
			"Rührei",
			"Grogonzola",
			"Pizza",
			"Gammelfleisch",
			"Auswurf",
			"Kotze",
			"Stuhlgang",
			"Mist",
			"Dreck",
			"Abfall",
			"Darmausscheidungen",
			"Butter",
			"Quark",
			"Erbsensuppe"
		],
		food_action : [
			"einreiben",
			"füttern",
			"bewerfen",
			"quälen",
			"steinigen",
			"vergewaltigen",
			"entjungfern"
		],
		food_action_passive : [
			"einführen",
			"ins Maul stopfen",
			"mit einer Spritzpistole in die Fresse spritzen",
			"ins Ohr stecken",
			"in die Nase rammen",
			"in die Schuhe kippen",
			"in den USB-Port stecken",
			"per E-Mail schicken",
			"über den ganzen Körper schmieren",
			"in die Hose stecken",
			"ins Bett legen",
			"zu Fressen geben"
		],
		verb : [
			"Sterben",
			"Kacken",
			"Sperma Schlucken",
			"Gammeln",
			"Anschaffen",
			"Porree Essen",
			"Haaren",
			"Furzen",
			"Anal Einführen",
			"Lutschen",
			"Anranzen",
			"Scheißen",
			"Fassen",
			"Koten",
			"Wursten",
			"Fliegen essen",
			"Katzen ficken",
			"Bäume knutschen",
			"Kühlschranktüren ficken",
			"Kot fressen",
			"Abgammeln",
			"Heulen",
			"Weinen",
			"Fisten",
			"Schwänze Lutschen",
			"Betteln",
			"Schnuppern"
		],
		genitals : [
			"Vagina",
			"Eier",
			"Eichel",
			"Nippel",
			"Testikel",
			"Muschi",
			"Hoden",
			"Pickel",
			"Pussy",
			"Schwanz",
			"Penis",
			"Eierstöcke",
			"Schritt",
			"Nase"
		],
		genital_action : [
			"Leck",
			"Schleck",
			"Lutsch",
			"Friss",
			"Schnüffel",
			"Inhalier",
			"Kraul",
			"Kotz",
			"Rubbel",
			"Sabber"
		],
		genital_action_hurt : [
			"trete",
			"schlage",
			"ficke",
			"wichse",
			"kneife",
			"pieke",
			"beisse",
			"penetriere",
			"zerstöre",
			"breche"
		]
	};

	var unspecificSentences = [
		'Geh {{verb}}, du {{attribute}}{{subject}}.',
		'{{attribute}}{{subject}}. Warum gehst du nicht einfach {{verb}}?',
		'Du bist {{attribute}}, du {{attribute}}{{subject}}.',
		'Ich {{genital_action_hurt}} dir in die {{genitals}}, du {{attribute}}{{subject}}.',
		'{{genital_action}} mir die {{genitals}}, {{attribute}}{{subject}}.',
		'Geh doch auf deine {{genitals}} {{verb}}, du {{attribute}}{{subject}}.',
		'Warum darf so ein {{attribute}}{{subject}} wie du überhaupt rumlaufen?',
		'Ich werde dir {{food}} {{food_action_passive}}, {{attribute}}{{subject}}.',
		'Ich werde dich mit {{food}} {{food_action}}, {{attribute}}{{subject}}.',
		'Ey, du {{attribute}}{{subject}}. Geh dich mit {{food}} {{food_action}}!',
		'Ey, du {{attribute}}{{subject}}. Geh dir {{food}} {{food_action_passive}}!'
	];

	specificSentences = [
		'Geh {{verb}}, {{ziel}}, du {{attribute}}{{subject}}.',
		'{{ziel}}! Warum gehst du nicht einfach {{verb}}?',
		'Du bist {{attribute}}, {{ziel}}.',
		'Ich {{genital_action_hurt}} {{ziel}} in die {{genitals}}.',
		'{{genital_action}} mir die {{genitals}}, {{ziel}}.',
		'Geh doch auf deine {{genitals}} {{verb}},{{ziel}}.',
		'Warum darf so ein {{attribute}}{{subject}} wie {{ziel}} überhaupt rumlaufen?',
		'Ich werde {{ziel}} {{food}} {{food_action_passive}}, {{attribute}}{{subject}}.',
		'Ich werde {{ziel}} mit {{food}} {{food_action}}, {{attribute}}{{subject}}.',
		'Yo, {{ziel}}, du {{attribute}}{{subject}}. Geh dich mit {{food}} {{food_action}}!',
		'{{ziel}}! {{attribute}}{{subject}}. Geh dir {{food}} {{food_action_passive}}!',
		'{{ziel}} ist ein {{attribute}}{{subject}}.',
		'Lasst uns alle {{ziel}}s {{genitals}} mit {{food}} {{food_action}}!'
	];

	function unspecificTarget() {
		bot.say(instrument(unspecificSentences, words));
	}

	function specificTarget(you) {
		bot.say(instrument(specificSentences, words, {
			ziel : you
		}));
	}
	bot.database.getAllIdentifiers(function(err, identifiers) {
		if(err) {
			Winston.error("Could not get all identifiers", err);
		}
		else {
			var arguments = [];
			for(var i in identifiers) { arguments.push(identifiers[i].identifier); }
			bot.newCommand("insult person", function(user, via, target) {
				bot.database.getUserByIdentifier(target, function(err, user) {
					if(err) {
						Winston.error("Unabled to get user by identifier: " + target, err);
						unspecificTarget();
					}
					else {
						if(user) {
							specificTarget(user.username);
						}
						else {
							unspecificTarget();
						}
					}
				});
			}, "Zufällig generierte Beleidigung einer Person an den Kopf werfen.", "bomb", arguments);
		}
		bot.newCommand("insult", function(user, via, target) {
			unspecificTarget();
		}, "Zufällig generierte Beleidigung.", "fire");
		callback();
	});

	return true;
};
